export const ADMIN_NAV_PERMISSIONS = {
    analytics: ["analytics:view_revenue", "analytics:track_margin", "analytics:*"],
    orders: ["orders:read", "orders:*"],
    serviceRequests: ["service_requests:read", "service_requests:*"],
    pricingReview: ["pricing:review", "pricing:adjust", "pricing:*"],
    pendingApproval: ["pricing:adjust", "pricing:admin_approve", "pricing:*"],
    lineItemRequests: ["line_item_requests:read", "line_item_requests:*"],
    workflowInbox: ["workflow_requests:read", "workflow_requests:*"],
    conditions: [
        "conditions:view_history",
        "conditions:update",
        "conditions:view_items_needing_attention",
        "conditions:*",
    ],
    invoices: ["invoices:read", "invoices:generate", "invoices:*"],
    reports: ["orders:export", "analytics:view_revenue", "assets:read", "orders:*", "analytics:*"],
    notifications: ["notifications:view_failed", "lifecycle:receive_notifications"],
    eventCalendar: ["calendar:read", "calendar:*"],
    users: ["users:read", "users:*"],
    companies: ["companies:read", "companies:*"],
    warehouses: ["warehouses:read", "warehouses:*"],
    zones: ["zones:read", "zones:create", "zones:update", "zones:delete", "zones:*"],
    brands: ["brands:read", "brands:*"],
    assets: ["assets:read", "assets:*"],
    collections: ["collections:read", "collections:*"],
    inboundRequest: ["inbound_requests:read", "inbound_requests:*"],
    teams: ["teams:read", "teams:*"],
    platformSettings: ["platform_settings:read", "platform_settings:*"],
    notificationRules: ["notification_rules:read", "notification_rules:*"],
    attachmentTypes: ["attachment_types:read", "attachment_types:*"],
    workflowDefinitions: ["workflow_definitions:read", "workflow_definitions:*"],
    accessPolicies: ["access_policies:read", "access_policies:*"],
    serviceTypes: ["service_types:manage", "service_types:*"],
    warehouseOpsRates: ["warehouse_ops_rates:read", "warehouse_ops_rates:*"],
    countries: ["countries:read", "countries:*"],
    cities: ["cities:read", "cities:*"],
    resetPassword: ["auth:reset_password", "auth:*"],
    selfBookings: ["self_bookings:read", "self_bookings:create", "self_bookings:*"],
    selfPickups: ["self_pickups:read", "self_pickups:*"],
} as const;

export const ADMIN_PAGE_PERMISSIONS = {
    analytics: "analytics:view_page",
    orders: "orders:view_page",
    serviceRequests: "service_requests:view_page",
    workflowInbox: "workflow_requests:view_page",
    pendingApproval: "orders:view_pending_approval_page",
    lineItemRequests: "line_item_requests:view_page",
    selfBookings: "self_bookings:view_page",
    selfPickups: "self_pickups:view_page",
    eventCalendar: "calendar:view_page",
    invoices: "invoices:view_page",
    reports: "analytics:view_reports_page",
    assets: "assets:view_page",
    collections: "collections:view_page",
    inboundRequest: "inbound_requests:view_page",
    conditions: "conditions:view_page",
    warehouses: "warehouses:view_page",
    zones: "zones:view_page",
    users: "users:view_page",
    companies: "companies:view_page",
    brands: "brands:view_page",
    teams: "teams:view_page",
    platformSettings: "platform_settings:view_page",
    notificationRules: "notification_rules:view_page",
    attachmentTypes: "attachment_types:view_page",
    workflowDefinitions: "workflow_definitions:view_page",
    accessPolicies: "access_policies:view_page",
    serviceTypes: "service_types:view_page",
    warehouseOpsRates: "warehouse_ops_rates:view_page",
    countries: "countries:view_page",
    cities: "cities:view_page",
} as const;

export const ADMIN_ACTION_PERMISSIONS = {
    ordersRead: "orders:read",
    ordersUpdate: "orders:update",
    ordersExport: "orders:export",
    ordersAddJobNumber: "orders:add_job_number",
    ordersAddTimeWindows: "orders:add_time_windows",
    ordersCancel: "orders:cancel",
    ordersSubmitForApproval: "pricing:review",
    ordersPricingAdjust: "pricing:adjust",
    ordersPricingAdminApprove: "pricing:admin_approve",
    ordersDownloadGoodsForm: "orders:read",
    invoicesRead: "invoices:read",
    invoicesGenerate: "invoices:generate",
    invoicesDownload: "invoices:download",
    invoicesConfirmPayment: "invoices:confirm_payment",
    companiesCreate: "companies:create",
    companiesUpdate: "companies:update",
    companiesArchive: "companies:archive",
    warehousesCreate: "warehouses:create",
    warehousesUpdate: "warehouses:update",
    warehousesArchive: "warehouses:archive",
    zonesCreate: "zones:create",
    zonesUpdate: "zones:update",
    zonesDelete: "zones:delete",
    assetsCreate: "assets:create",
    assetsRead: "assets:read",
    assetsUpdate: "assets:update",
    assetsDelete: "assets:delete",
    assetsBulkUpload: "assets:bulk_upload",
    collectionsCreate: "collections:create",
    collectionsRead: "collections:read",
    collectionsUpdate: "collections:update",
    collectionsDelete: "collections:delete",
    usersManagePassword: "users:manage_password",
    inboundRequestsCreate: "inbound_requests:create",
    serviceRequestsCreate: "service_requests:create",
    warehouseOpsRatesRead: "warehouse_ops_rates:read",
    warehouseOpsRatesUpdate: "warehouse_ops_rates:update",
    // Self-pickup actions — mirror orders' naming (SP4 of self-pickup parity sprint).
    selfPickupsRead: "self_pickups:read",
    selfPickupsCancel: "self_pickups:cancel",
    selfPickupsSubmitForApproval: "pricing:review",
    selfPickupsPricingAdjust: "pricing:adjust",
    selfPickupsPricingAdminApprove: "pricing:admin_approve",
    selfPickupsMarkNoCost: "self_pickups:mark_no_cost",
} as const;
